### PR TITLE
chore: Use literal providers and remove hard peerDependency on Angular 2

### PR DESCRIPTION
**Pull request by MikeRyanDev**

### CODE REVIEW

**Comment by MikeRyanDev** [comment]
Note that while this PR removes the peerDependency on Angular 2, upstream dependency @ngrx/core still needs it for the time being.

**Comment by robwormald** [comment]
LGTM 👍

**Comment by MikeRyanDev** [comment]
@robwormald I noticed in angular/vladivostok you moved the [provider factories out of the provider definitions](https://github.com/angular/vladivostok/commit/3c9ee5099f4d96df291b3d7c49333217b58e5ff4). Is this required to make to the provide statements offline compiler friendly? If so I'll send over another PR to make that change.

**Comment by MikeRyanDev** [comment]
Dependency on Angular 2 has been removed from @ngrx/core. After this is published to npm, it should be easier to use ngrx/store in non-Angular 2 projects.

**Comment by Hotell** [comment]
Nice! Now the integration with Angular 1 via ng-metadata will be a no brainer. 👍

**Pull request merged**
