### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by btroncone**
Added link to @ngrx/store introduction gist to help beginners.

### CODE REVIEW

**Comment by MikeRyanDev** [comment]
I think you should also add a link to your Egghead series (it doesn't require a subscription, right?)

**Comment by btroncone** [comment]
Sounds good, I included a link. No subscription is required. :smile:

**Comment by fxck** [comment]
and Rob's talk

**Comment by btroncone** [comment]
Absolutely, updated. :+1:

**Comment by btroncone** [comment]
No longer necessary w/ new readme.

**Pull request closed without merging**
