### PR TITLE
refactor(Store): Remove SyncSubjects and correctly subclass Observable

### PR DESCRIPTION
**Pull request by MikeRyanDev**
Replaces all SyncSubjects with BehaviorSubjects. Use an Observable for Store, subclassing it correctly

cc @blesh @petebacondarwin @brandonroberts

### CODE REVIEW

**Comment by frederikschubert** [comment]
Would this mean that the reducers and store are run asynchronously? That would be great!

**Comment by petebacondarwin** [comment]
@frederikschubert - all this means is that the `store` is now created from the lower level basic building blocks of the Obervable types rather than on top of a higher level abstraction.

I am not an expert but I believe that Observables and RxJS is agnostic about running things async. You should be able to control it via Schedulers right?

**Comment by jimitndiaye** [comment]
Could this be why I was having instances of where store state and reducer state seemed to be out of sync when dispatching actions asynchronously? I'd have an action come through a reducer and I'd see the the output state has changed then when the next action comes through the state had reverted.

**Comment by MikeRyanDev** [comment]
@jimitndiaye No, this shouldn't have any behavior changes. This is entirely internal to make future RxJS upgrades easier.

**Comment by utopizetetes** [comment]
Isn't making Store subclass Observable instead of SyncSubject going to change some behaviors? At least, observers will not receive the most recent value upon subscription. It is likely that some code is written with this characteristic in mind. For example,

`someObservable.switchMapTo(store).subscribe(doSomething);`

now will fire doSomething only after there is new update in store. If the author of this line intends to execute doSomething upon there is a new value in someObservable, the change in this commit seems to lead to unexpected behaviors.

Maybe there is another way to get the intended result; however there would be an inevitable change in code.

@MikeRyan52 would you share your ideas about this? Thank you!

**Comment by MikeRyanDev** [comment]
@Doraemon09032012 The underlying `State` service is still a `BehaviorSubject` and will continue to deliver the last value synchronously. `Store`'s observable source points to the `State` subject so the behavior of subscribing to `Store` remains unchanged. It will continue to deliver the last value synchronously and the state stream will still to be shared.

**Pull request merged**
