### PR TITLE
Update Angular 4.0.0-rc1 to 4.0.1

### PR DESCRIPTION
**Pull request by sliekens**
I propose updating the dependency on Angular to version 4.0.1.
I have not tested this change. If you think this change is breaking, let's talk.

**Edit**
Just to clarify: this commit does _not_ impose strict versions on **consumers** of this package. This commit does restrict the version for **developers** of this package to version 4.0.1.

Old situation
- dev dependencies: restricted to version `4.0.0-rc.1`
- peer dependencies: restricted to version `4.0.0-rc.1`

New situation
- dev dependencies: restricted to version `4.0.1`
- peer dependencies: restricted to versions `>=4.0.0 <5.0.0`

### CODE REVIEW

**Comment by PG2000** [comment]
@robwormald 
Would it be possible to accept this pull request ?

**Comment by mscudlik** [comment]
i think it is not a good idea to add a hard dependency to i minor version, because the same issue we have now will happen if 4.0.2 will be released

**Comment by sliekens** [comment]
The dependencies that have a minor version are just dev dependencies. I believe it's better to lock dev dependencies down to a specific version.

There is also a peer dependency that was locked down to rc.1 and I changed it to accept any major version of Angular 4.

I updated my original post to clarify this.

**Comment by dietergoetelen** [comment]
I've tested this PR and I also had to add/update the following dependencies to make it work: 

- Zone.JS: ^0.8.4
- @angular/animations: 4.0.1
- Typescript: ^2.2.1

**Comment by sliekens** [comment]
Thanks for the information. I will add commits for those versions.

**Comment by sliekens** [comment]
I updated my pull request with the feedback from @dietergoetelen

**Comment by brandonroberts** [comment]
@StevenLiekens we are currently moving the ngrx packages to a monorepo here: https://github.com/ngrx/platform which already includes the latest dependencies

**Comment by sliekens** [comment]
That is great news. Thanks for the link.

**Pull request closed without merging**
