### PR TITLE
Added rxjs to package.json and updated tsconfig.json with missing files

### PR DESCRIPTION
**Pull request by chessydk**

### CODE REVIEW

**Comment by fxck** [comment]
remove those .idea files

**Comment by chessydk** [comment]
Done. Sorry about that.

**Comment by robwormald** [comment]
RxJS is included as a peerDependency, on purpose - it's expected that it would be installed with Angular2 and peer dependencies avoids a possible version conflict. 

Typescript automatically transpiles files referenced, so including them all is unnecessary.

Was there a particular reason you made both of these changes?

**Comment by chessydk** [comment]
Thx. for teaching a newbie - been reading up on peer-dependencies, check! Regarding the typescript files: yep - compilation works fine, I just (or rather webstorm) noted that the list of files was incomplete and thought that to be a mistake.

**Comment by robwormald** [comment]
No worries! Thanks for the PR anyway 👍

**Pull request closed without merging**
