### PR TITLE
update reducer declaration for ngc

### PR DESCRIPTION
**Pull request by awerlang**
Small change but I imagine this is what most people would be doing from now on.

### CODE REVIEW

**Comment by fxck** [comment]
Wait, can you not use these constant functions when you want to use ngc? Why? Is there a list of things you need to do to be compatible with ngc?

**Comment by awerlang** [comment]
A lambda assigned to a const is a function expression, not a function declaration. `ngc` interprets them as different things because it only analyses code statically. 

Here's a small list I put together:
- const lambda => export function
- default export => named export
- moduleId should be set on components with templateUrl
- dynamic component template => static template
- private, protected acessors should be changed to public for any members accessed from template

**Comment by fxck** [comment]
Man that's a bummer..

**Comment by awerlang** [comment]
I'm okay about these required changes. For instance the last one, you can get typecheck for your templates! And maybe they get to support the first 3 on a later version.

**Comment by tschuege** [comment]
What is the state on this? 
I'm getting the following error when using ng-xi18n and I think it is related to this.
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol INITIAL_REDUCER in /home/.../node_modules/@ngrx/store/src/ng2.d.ts

**Comment by awerlang** [comment]
@tschuege This issue seems to be fixed since v2.1.0. Anyways, it is unrelated to this PR. This covers docs only.

**Comment by brandonroberts** [comment]
Closed via https://github.com/ngrx/store/pull/306

**Pull request closed without merging**
