### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by criticalbh**
`provideStore` instead of `forRoot` in StoreModule

### CODE REVIEW

**Comment by dannypule** [comment]
Why hasn't anyone merged this in yet? It's a simple fix which would have saved me 15 mins of pain.

**Comment by kylecordes** [comment]
This thing caught me up also, and I've been using Store a long time. Was surprised to be led astray for a few minutes by the current live README, consulted a couple examples instead to get a new app up and going.

**Comment by brandonroberts** [comment]
`StoreModule.forRoot` and `StoreModule.forFeature` is the syntax that will be used in the next major release which as been merged into master. The docs will be updated accordingly.

**Comment by fxck** [comment]
What's up with `@ngrx/platform` and new v4 of store, effects @brandonroberts? Are you waiting until after ng-conf, or @MikeRyan52 is just busy at work?

**Comment by JoshWilliams92** [comment]
Changing 'StoreModule.forRoot' to 'StoreModule.provideStore' in the app.module file seemed to fix the issue for me. Thanks @criticalbh

**Pull request closed without merging**
