### PR TITLE
feature(store): add ability to add reducer on the fly

### PR DESCRIPTION
**Pull request by robwormald**

### CODE REVIEW

**Comment by robwormald** [comment]
i'm 50/50 on the interface here:

``` js
store.addReducer(name:string, reducer:Reducer, initialState:any);
```

or

``` js
store.addReducers(reducersObj:{[key:string]:Reducer}, initialState:{[key:string]:any});
```

i'm leaning towards the latter as it better matches the initial setup, but i could go either way.

also: do we need a removeReducer(s)? that would need to take a `string` or `string[]` so there's a bit of a mismatch with option2.

**Comment by robwormald** [comment]
this also has the nice side effect of forcing more of the logic to be in the store and less in the provideReducer function, which is :+1:

**Comment by cschiavolini** [comment]
> i'm leaning towards the latter as it better matches the initial setup 

I agree with you that the object signature is more in line with how one creates the store initially 

About removeReducers, I am not sure if there is a clear use case. 
Anyway you could have an uniform signature by having an `updateReducers` instead of `addReducers`. If the set of reducers supplied is empty it is very similar to deleting them. 

I leave to you to say if this change of API is useful or counter intuitive

**Comment by meenie** [comment]
This will be awesome! You can leave most, if not all, of the reducer setup code out of the bootstrap and have one for each of the top level containers of your app.  Makes the app very modular; as is the goal of this PR :).  

@cschiavolini: Great suggestion!!

**Pull request merged**
