### PR TITLE
refactor(): Refactor core to remove middleware and simplify internals

### PR DESCRIPTION
**Pull request by MikeRyanDev**
BREAKING CHANGE:
    Middleware is no longer supported. There are no plans to re-implement this feature.

BREAKING CHANGE:
    `getState()`, `getValue()`, and `value` have been removed from `Store`. Instead, subscribe will deliver the last value synchronously.

### CODE REVIEW

**Comment by fxck** [comment]
Nice!

**Comment by MikeRyanDev** [comment]
I can add `select` back to Store pretty easily if that's what everyone would prefer. Three options really:
- Leave as is, not on any observable
- Add just to Store
- Add to all observables

**Comment by btroncone** [comment]
For quality of life I would vote to leave it 'as is'. I can already imagine the never ending stream of GitHub issues if it needs to be manually imported.

**Comment by robwormald** [comment]
let's leave it on the Store observable by default

**Comment by btroncone** [comment]
My only concern is the setup process and applying of meta-reducers (logger, localstorage, etc) that act like middleware is significantly more harsh with this update. For example, currently setting up store and applying logger and localstorage middleware looks something like this:

``` ts
return bootstrap(TodoApp, [
      provideStore({todos, visibilityFilter}),
      ...localStorageMiddleware('stateKey')
      ...loggerMiddleware()
  ])
```

The current change would make it look something like this: (taken from previous thread example)

``` ts
const reducer = compose(logChanges, curry(keepInLocalStorage)('stateKey'), combineReducers)({
  todos: reduceTodos,
  filter: reduceFilter
});
return bootstrap(TodoApp, [
      provideStore(reducer)
  ])
```

It's not a huge change, but I do think it's harder for new users to wrap their head around. Is there any way to smooth this out? Or maybe I'm exaggerating, would love to hear others thoughts. Just my two cents. :+1:

**Comment by MikeRyanDev** [comment]
Updated to put `select()` back on `Store`

**Comment by MikeRyanDev** [comment]
@btroncone As a big fan of functional-style programming, that code example looks like the dream :) 

Seriously though, I'd be open to API suggestions on how to make it less functional.

**Comment by laurelnaiad** [comment]
@btroncone I feel like in the absence of middleware, there's a bit too much of a vacuum in the API. If one wishes to get code to run in front (of the observable chain) that feeds the true root reducer, there are no rails or guideposts. I think we're supposed to hold our breath and hope the effect api fills the vacuum well enough for all of the use cases that seem prominent in our apps. I'm really looking forward to knowing more about that before I know whether or not I love the idea of yanking the current middleware. That all said, I trust that I'm in good hands, so I'm not running around with a pitchfork.

**Comment by laurelnaiad** [comment]
Would we be able to do the equivalent of post-middleware in the tail of a composed function after the dispatcher?

(EDIT: One of the reasons I'm asking is because my code assumes sagas see actions after the reducer)

**Comment by btroncone** [comment]
@MikeRyan52 I enjoy that style myself, I'm just worried we may be in the minority when we compare the two examples. Although I guess people have gotten used to the amount of currying in Redux API so I can assume devs will learn and adapt. 

(Edit: Other then logger, local storage, and saga (presumably filled by effect) I'm not sure what 'middleware' is even necessary. I think I'm overreacting.)

@laurelnaiad I definitely feel your concern and also trust we will reach an awesome place before all is said and done. :)

**Comment by iamdey** [comment]
First I follow this repository since while (1 or 2 months) and I'm a redux/angular2 enthusiastic but still not an expert.

So I would like to understand why this decision. 

I know this not redux and ngrx/store should has its own life but I'm a bit confused because I believed there were almost no intelligence in actions and almost no in reducers too and controllers capture browser events. So I just see that real business logic should go into middlewares.

I would appreciate some explanations, real world example or any kind of articles that make this clearer (also it could be linked to this commit or documentation for other people).

**Comment by kylecordes** [comment]
@iamdey Someone else will likely explain more... but here is one key part of the answer. The heart of a system built with this architecture is the reducers. That is where most of the logic lands.

**Comment by robwormald** [comment]
some thoughts 
- reducers feel like the wrong place for localStorage, given that its quite side-effect-y 
- re the reducer composition stuff, i'm not a huuuge fan of the curry'ing because its sort of hard to understand for non-functional minded people.

perhaps we should split the config API (i'd typically argue against this, but yolo):
- `provideStore(objectOfKeysAndReducers, objectOfInitialStates)`
- `provideRootReducer(curryAsMuchAsYouDamnWellPlease, initialState)`

I prefer the former simply because it sticks to the database/tables idea I have in my head and doesn't obfuscate what's actually going on, but I get that some people want to do a more functional-enhancement approach. 

What if I only want to implement undo/redo on one reducer? It's simpler to do (imo)

``` typescript

{ 
  foos: fooReducer,
  bars: makeUndoableReducer(barReducer)
}

```

No?

**Comment by kylecordes** [comment]
Regarding the initial states in the APIs above, is this the recommended pattern? Looking around a lot of what I found in the redux world, and possibly even including an NgRx example (I don't remember for sure), I got the impression that it is typical for a reducer to automatically put in a default initial state when reducing an initially empty state. I'm not sure whether this makes more or less sense than explicitly building the initial states all the way up to the top to use an API is shown. The downside is that you end up repeating the same construction of reducers parallel to a construction of initial state.

Regarding the question of whether to provide an object of keys and reducers versus a single root reducer, I have found that the former is an obstacle to learning. When working with a group of developers here getting up to speed on this overall approach, the special privileged top-level set of reducers got in the way of understanding the process of building up various reducers hierarchically to manage a complex state. However, maybe this is intentional, so as to discourage excessive hierarchy in state shape and encourage a wide, flat arrangement.

**Comment by MikeRyanDev** [comment]
@robwormald @kylecordes `provideStore()` is already polymorphic and will accept key/value pairs or a single reducer function. I also decided against removing the automatic combination for ease-of-access.

**Comment by MikeRyanDev** [comment]
See https://github.com/ngrx/store/blob/ca8c967bbe70cd7f57bacf5a8cbc8adfe7cec21b/src/ng2.ts#L46

**Comment by kylecordes** [comment]
@MikeRyan52 Thanks, I will aim to remember to use the single reducer variation when explaining to avoid the trip up I described.

**Comment by robwormald** [comment]
@kylecordes the reason for the initialState external API (vs using defaults on reducers, which is totally fine) is initial state hydration from a server side rendering scenario.

**Comment by btroncone** [comment]
@robwormald While I agree local storage is side-effecty, where would you suggest this move? This and logging are two very (most?) popular use-cases that get orphaned with the removal of middleware. I think this functionality needs to be maintained in some capacity.

**Comment by fxck** [comment]
- would be nice if `whenAction` was `whenActions` and accepted multiple actions
- operator for `.do().filter(() => false)` usecase would be nice 
- how to set `StateUpdates.state` type?

**Comment by fxck** [comment]
Another thing, 

```
    this._effects
      .onInviteSuccess$
      .takeUntil(this._ngOnDestroy$)
      .subscribe(this._store);
```

this will stil break evething(ObjectUnsubscribedError), this is still needed `.subscribe(res => this._store.next(res)`, I remember you saying you will fix it @MikeRyan52

**Comment by NathanWalker** [comment]
@MikeRyan52 you're my hero, hopefully the migration guide on readme is _all_ we need to know with the changes from this?

**Comment by MikeRyanDev** [comment]
Yes, that's all that has been changed :) The package hasn't been published to npm. Will hopefully make it out later tonight or early tomorrow.

**Pull request merged**
