### PR TITLE
README.md update ~ SystemJS set up (#123)

### PR DESCRIPTION
**Pull request by kinggolf**
Took liberty to create this PR, since I ran into same issue as @silentHoo. Not sure this belongs in the README. Recently submitted example app by @pavanpodila, #133, seems to cover this. However, I found this blog that got me on the right track, https://ng2learnings.wordpress.com/2016/04/30/angular-cli-and-ngrx/.

### CODE REVIEW

**Comment by kinggolf** [comment]
@robwormald or others - I am happy to help out with some other changes on @ngrx. I really enjoy using this library and appreciate everyone's time/effort. I just want to contribute where I can.  If I can help on updates to typings or whatever, then please point me in the right direction. Cheers.

**Comment by kinggolf** [comment]
Actually, the @ngrx/router has all the details required to explain this, so maybe just a simple link in @ngrx/store to the @ngrx/router documentation would be adequate. Happy to redo the PR if that is the way this should go.

**Comment by robwormald** [comment]
LGTM, thanks!

**Comment by btroncone** [comment]
@kinggolf I am going to add these directions to store docs as well, thanks! :+1:

**Pull request merged**
