### PR TITLE
feat(Dispatcher): Change dispatcher to replay last action

### PR DESCRIPTION
**Pull request by MikeRyanDev**
To correctly implement store-saga without middleware, I need to be able to create an observable that has the most recent state change and the action that caused that change. Best operator path seems to be:

``` ts
store.withLatestFrom(dispatcher, (state, action) => ({ state, action }));
```

Unfortunately, this doesn't keep them in sync because store is replaying its last value. This changes the dispatcher to also replay one value.

### CODE REVIEW

**Comment by MikeRyanDev** [comment]
Of course, I'm open to other options as well!

**Comment by nosachamos** [comment]
@MikeRyan52 since you only need to replay one value, wouldn't a BehaviorSubject suffice?

**Comment by MikeRyanDev** [comment]
@nosachamos It would suffice, but a BehaviorSubject does a little more than replay the last value; it also provides a synchronous way to get the most recent value out of the subject using `BehaviorSubject::getValue()`. This isn't necessary for the dispatcher.

**Comment by robwormald** [comment]
this is one of those things that makes me _really_ nervous, as its introducing state where there should be none. is this not something you can do in user-space / outside of core?

**Comment by nosachamos** [comment]
Both good points. Personally I don't think installing a middleware is a big deal, it could in fact be argued it helps the user by teaching how this magic takes place.

**Pull request closed without merging**
