### PR TITLE
chore(upgrade): upgrade @angular to rc.1

### PR DESCRIPTION
**Pull request by tamascsaba**

### CODE REVIEW

**Comment by tamascsaba** [comment]
@robwormald, @MikeRyan52????

**Comment by sentyaev** [comment]
we totally need this to happen

**Comment by laurelnaiad** [comment]
Why do you need this to happen?

You can use rc.1 right now (because of the caret). Generally, in shared libraries, you should require the minimum version of your dependencies with which you are compatible.  ngrx/store is compatible with rc.0.

If you wish to use rc.1 you are free to do so, and ngrx/store will work just fine.

**Comment by sentyaev** [comment]
I totally agree with that in case we talk about 'stable' versions. Probably it because I worked with .NET Core and each new version (even RC) broke everything.
So, I'm glad that it's working with rc.1. Thanks for pointing that out!

**Comment by robwormald** [comment]
I'm going to leave store on rc0 unless we change anything major upstream on angular, until we get closer to a larger release. Cheers!

**Pull request closed without merging**
